#ifndef INC_METTLE_DRIVER_DETAIL_BENCODE_HPP
#define INC_METTLE_DRIVER_DETAIL_BENCODE_HPP

#ifdef METTLE_USE_STDLIB_EXTS
#  define BENCODE_USE_STDLIB_EXTS
#endif

#ifdef METTLE_NO_STDLIB_EXTS
#  define BENCODE_NO_STDLIB_EXTS
#endif

#include <bencode.hpp>

#endif
